### ISSUE TITLE
quickroam-insert inserts link at top of buffer, regardless of (point)

### ISSUE THREAD

**Issue by cashpw** [meedstrom/quickroam#3]
I expect `quickroam-insert` to insert in the same way `org-roam-node-insert` does, which is to insert the link at `(point)`. Instead, the link is inserted on the second line of the file and anything on that line is pushed to the side.

I suspect it's because of this bit:

```elisp
;; Try to strip the todo keyword, whatever counts as todo syntax
;; in the target file.  Fail silently because it matters not much.
(ignore-errors
  (org-roam-with-file
      (expand-file-name (plist-get node :file) org-roam-directory)
      nil
    (widen)
    (goto-char 1)
    (forward-line (1- (plist-get node :line-number)))
    (setq link-desc (nth 4 (org-heading-components)))))
```

I don't understand the purpose of this code. Is the title not an appropriate link description? What's that about stripping the `TODO` keyword? Does this assume something about the current buffer and/or the buffer of the node we've selected?

I restored my expected behavior by using a modified `quickroam-insert`:

```elisp
(defun cashpw/quickroam-insert ()
  "Fast substitute for `org-roam-node-insert'."
  (interactive nil org-mode)
  (require 'org-roam)
  (when (or (hash-table-empty-p quickroam-cache)
            (not quickroam-mode))
    (quickroam-reset))
  (let* ((beg nil)
         (end nil)
         (region-text (when (region-active-p)
                        (setq beg (region-beginning))
                        (setq end (region-end))
                        (org-link-display-format
                         (buffer-substring-no-properties beg end))))
         (title (completing-read "Node: " quickroam-cache nil nil nil 'org-roam-node-history))
         (node (gethash title quickroam-cache))
         (id (plist-get node :id))
         (link-desc (or region-text title)))
    (if node
        (atomic-change-group
          (when region-text
            (delete-region beg end))
          (insert (org-link-make-string (concat "id:" id) link-desc))
          (run-hook-with-args 'org-roam-post-node-insert-hook id link-desc))
      (atomic-change-group
        (org-roam-capture-
         :node (org-roam-node-create :title title)
         :props (append
                 (when region-text
                   (list :region (cons (set-marker (make-marker) beg)
                                       (set-marker (make-marker) end))))
                 (list :link-description link-desc
                       :finalize 'insert-link)))))))
```

**Comment by meedstrom** [comment]
I agree about the intended behavior.  Now that you point it out, I see the
code probably only worked well with file-level nodes - I’m guessing you’re
inserting links to subtrees in the same file?

The TODO stripping code needs to be wrapped in a save-excursion. I’ll fix
it when I get back to my computer, thanks for reporting!

(The purpose of that snippet is just, well, if you have nodes with a TODO
state, we don’t want to see the TODO state in the link, right?)

**Comment by meedstrom** [comment]
https://github.com/meedstrom/quickroam/commit/a5b5dda87e93099aac2afda16f06fb340bce7f5f fixed the behavior in my testing.
